name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # -------- BACKEND --------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish Backend
      run: |
        dotnet publish Backend/LifeHub-Backend.csproj -c Release -o publish/backend

    # -------- FRONTEND --------
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build Frontend
      run: |
        npm ci --prefix Frontend
        npm run build --prefix Frontend

        mkdir -p publish/frontend
        cp -r Frontend/dist/* publish/frontend/

    # -------- DEPLOY --------
    - name: Upload artifacts
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "publish"
        target: "/home/${{ secrets.VPS_USER }}"

    - name: Deploy via rsync
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          mkdir -p /var/www/lifehub/backend /var/www/lifehub/frontend

          rsync -av --delete ~/publish/backend/ /var/www/lifehub/backend/
          rsync -av --delete ~/publish/frontend/ /var/www/lifehub/frontend/

    - name: Update .env file on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          echo "Jwt__Key=${{ secrets.JWT_KEY }}" > /var/www/lifehub/backend/.env

    - name: Restart backend
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          sudo systemctl restart lifehub-backend
